spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: true
      uri: http://localhost:50100
      request-connect-timeout: 5000 #ms
      request-read-timeout: 5000 #ms
      fail-fast: true
      retry:
        max-attempts: 8
        initial-interval: 2000
        max-interval: 5000
        multiplier: 1.3
  r2dbc:
    url: r2dbc:postgresql://localhost:5032/polardb_order
  flyway:
    url: jdbc:postgresql://localhost:5032/polardb_order