spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    config:
      enabled: false
  r2dbc:
    username: polardb
    password: 
    url: r2dbc:postgresql://localhost:5590/polardb_order
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5590/polardb_order
  

server:
  port: 50201
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
    
polar:
  catalog-service-uri: "http://localhost:50101"
  home-message: Default Env, Welcome here