apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: management/prometheus
        prometheus.io/port: "50201"
    spec:
      containers:
        - name: order-service
          image: ghcr.io/ubaid4j/order-service:0.0.5-snapshot
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50201
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: 50201
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: 50201
            initialDelaySeconds: 5
            periodSeconds: 15
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
