apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ghcr.io/ubaid4j/order-service:0.0.1-snapshot
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50101
          env:
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://order-postgres/polardb_order
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://order-postgres/polardb_order
            - name: SPRING_R2DBC_USERNAME
              value: order
            - name: SPRING_R2DBC_PASSWORD
              value: order
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
              # TODO Create a minimal reproducible sample and create issue in spring boot repo
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
